config/routes.rb
Rails.application.routes.draw do
  get 'error/show'
  resources :events do
    collection { post :import }
  end
  resources :people

  get '/favourites', to: 'favourites#list', as: 'get_favourites'
  put '/rooms/:id/favourite', to: 'favourites#set_favourite_room', as: 'put_favourite_rooms'
  put '/buildings/:id/favourite', to: 'favourites#set_favourite_building', as: 'put_favourite_buildings'
  put '/locations/:id/favourite', to: 'favourites#set_favourite_location', as: 'put_favourite_locations'
  put '/people/:id/favourite', to: 'favourites#set_favourite_person', as: 'put_favourite_people'
  resources :rooms do
    get 'calendar'
  end

  resources :openingtimes
  resources :buildings
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # '/users/...'
  # https://github.com/plataformatec/devise#configuring-routes
  devise_for :users, path: 'users',
    controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  # '/login'
  get '/login', to: 'welcome#login'

  # '/building/map'
  get '/building_map/route', to: 'building_map#route'
  get '/building_map/view', to: 'building_map#view'

  # '/search_results'
  get '/search_results', to: 'search_results#index'

  put '/users/geo_location', to: 'users/geo_locations#update'
  delete '/users/geo_location', to: 'users/geo_locations#delete'

  # '/calendar'
  get '/calendar', to: 'calendar#show'

  # '/'
  # Sets `root_url`, devise gem requires this to be set
  root to: "welcome#index"

  get '/map/*path' => "welcome#index", as: 'map'

  get 'users/roles'
  put '/users/:id/roles', to: 'users#update_roles'
end

app/models/person.rb
# the model representing a person of interest
class Person < ApplicationRecord
  include Timeable
  include Favourable

  validates :phone_number, phone: true, allow_blank: true
  before_save :normalize_phone_number
  has_one_attached :profile_picture
  has_and_belongs_to_many :rooms
  has_and_belongs_to_many :owners, class_name: 'User', join_table: 'person_owner'

  accepts_nested_attributes_for :openingtimes, allow_destroy: true

  def formatted_phone_number
    parsed_phone = Phonelib.parse(phone_number)
    return number_to_phone(phone_number) if parsed_phone.invalid?

    parsed_phone.full_international
  end

  def name
    "#{first_name} #{last_name}"
  end

  def self.from_omniauth(auth)
    person = new
    person.first_name = auth.info.first_name
    person.last_name = auth.info.last_name
    person.email = auth.info.email
    person
  end

  def corresponding_user
    # FIXME: This feels like Rails should have this built-in, but I couldn't
    # find anything
    User.find_by person: self
  end

  def search_description
    "#{I18n.t(:email)}: #{email}"
  end

  private

  def normalize_phone_number
    self.phone_number = Phonelib.parse(phone_number).full_e164.presence
  end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: %i[show edit update destroy]
  before_action :add_person, only: %i[create]

  load_and_authorize_resource
  # GET /people or /people.json
  def index
    @people = Person.all
  end

  # GET /people/1 or /people/1.json
  def show; end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit; end

  # POST /people or /people.json
  # rubocop:disable Metrics/MethodLength
  def create
    @person.owners = [current_user]
    respond_to do |format|
      if @person.save
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.create', model: t('people.one'))
        end
        format.json { render :edit, status: :created, location: @person }
      else
        render_errors format, :new
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /people/1 or /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.update', model: t('people.one'))
        end
        format.json { render :edit, status: :ok, location: @person }
      else
        render_errors format, :edit
      end
    end
  end

  # DELETE /people/1 or /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html do
        redirect_to edit_user_registration_path, notice: t('model.success.destroy', model: t('people.one'))
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_person
    @person = Person.find(params[:id])
  end

  def add_person
    @person = Person.new(person_params)
  end

  def render_errors(format, route)
    format.html { render route, status: :unprocessable_entity }
    format.json { render json: @person.errors, status: :unprocessable_entity }
  end

  # Only allow a list of trusted parameters through.
  def person_params
    params.require(:person).permit(:phone_number, :first_name, :last_name, :email, { room_ids: [] }, :profile_picture,
                                   { openingtimes_attributes: [:id, :day, :opens, :closes] })
  end
end

app/helpers/people_helper.rb
module PeopleHelper
  def tel_to(phone_number)
    link_to phone_number, "tel:#{phone_number}"
  end

  def mail_to(email)
    link_to email, "mailto:#{email}"
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person) do |form| %>

  <%= render 'form_fields', form: form, person: @person %>

  <div class="actions mt-3">
    <%= form.submit class: "btn btn-primary" %>
  </div>

<% end %>

app/views/people/_form_fields.html.erb
<% if person.errors.any? %>
  <div id="error_explanation">
    <h2><%= t('errors.template.header', count: person.errors.count, model: t('people.one')) %></h2>

    <ul>
      <% person.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="field mb-3 profile-picture edit-profile-picture">
  <%= form.label t('people.profile_picture'), class: 'form-label' %>
  <div class='profile-picture-wrapper'>
    <div class='profile-picture-container'>
      <% if person.profile_picture.attached? %>
        <img src="<%=(url_for(person.profile_picture))%>" alt="<%= person.profile_picture.filename %>"/>
      <% else %>
        <%= image_tag "default-profile-picture.png", alt: "default-profile-picture"%>
      <% end %>
    </div>
    <button class='edit-btn' onclick="event.preventDefault(); $('input[type=file]').click()"><i class="fa fa-pen" aria-hidden="true"></i></button>
  </div>
  <%= form.file_field :profile_picture, class: 'form-control', accept: 'image/png,image/jpeg' %>
</div>

<div class="field mb-3">
  <%= form.label t('people.first_name'), class: 'form-label' %>
  <%= form.text_field :first_name, class: 'form-control' %>
</div>

<div class="field mb-3">
  <%= form.label  t('people.last_name'), class: 'form-label' %>
  <%= form.text_field :last_name, class: 'form-control' %>
</div>

<div class="field mb-3">
  <%= form.label  t('people.phone_number'), class: 'form-label' %>
  <%= form.text_field :phone_number, class: 'form-control' %>
</div>

<div class="field mb-3">
  <%= form.label t(:email), class: 'form-label' %>
  <%= form.text_field :email, class: 'form-control' %>
</div>

<div class="field mb-3">
  <%= form.label t('rooms.other'), class: 'form-label' %><br/>
  <%= form.select 'room_ids',
                  options_from_collection_for_select(Room.all, :id, :name, person.room_ids),
                  {},
                  multiple: true, class: 'form-control' %>
</div>

<div class="field mb-3 opening-times-container">
  <%= form.label t('people.office_hour.other'), class: 'form-label' %>
  <%= form.fields_for :openingtimes do |o| %>
    <div class="field mb-3 input-group" id="opening-time-field-<%= o.object.id %>">
      <%= o.select 'day',
                   options_for_select(Openingtime.day_string_to_number_mapping, o.object.day),
                   {},
                   multiple: false, class: "form-control form-inline" %>
      <%= o.time_field :opens, value: o.object.opens, class: "form-control form-inline" %>
      <div class="input-group-text">-</div>
      <%= o.time_field :closes, value: o.object.closes, class: "form-control form-inline" %>
      <%= link_to(openingtime_path(o.object.id), :method => :delete, :class => 'btn btn-mini',
                  :remote => true, :onclick =>
                    "{$('#opening-time-field-#{o.object.id}').next().remove();
                     $('#opening-time-field-#{o.object.id}')[0].remove()}") do %>
        <i class="fas fa-trash"></i>
      <% end %>
    </div>
  <% end %>
  <button class="btn" onclick="event.preventDefault(); addNewOpeningTime(this);" >
    <i class="fas fa-plus"></i><%= " #{t('model.add_new', model: t('people.office_hour.one'))}" %>
  </button>
</div>

<script defer>
    // Identify whether the fields are rendered on the users edit page, which renders these in a sub-form.
    // Otherwise they are located on the plain persons edit page.
    const onUsersEditPage = $('form.edit_user').length > 0;
    const fieldPrefix = onUsersEditPage ? 'user[person_attributes]' : 'person';

    const profilePictureInput = $(`input[name="${fieldPrefix}[profile_picture]"]`);
    profilePictureInput.change(function () {
        const file = $(this).prop('files')[0] || null;
        if (!file) {return; }
        const url = URL.createObjectURL(file);
        $('.profile-picture-container img').prop('src', url);
        $('.profile-picture-container img').prop('alt', file.name);
    })

    const options_html = `
  <% Openingtime.day_number_to_string_mapping.each do |number, string| %>
<option value=<%= number %>><%= string %></option>
  <% end %>`;

    var opening_time_index = <%= person.openingtimes.length %>
    const addNewOpeningTime = (target) => {
        $(`<div class="field mb-3 input-group" id="opening-time-field-new">
       <select name="${fieldPrefix}[openingtimes_attributes][` + opening_time_index + `][day]" id="opening-time-field-new" class="form-control form-inline">` + options_html + `</select>
       <input type="time" name="${fieldPrefix}[openingtimes_attributes][` + opening_time_index + `][opens]" id="opening-time-field-new" class="form-control form-inline">
       <div class="input-group-text">-</div>
       <input type="time" name="${fieldPrefix}[openingtimes_attributes][` + opening_time_index + `][closes]" id="opening-time-field-new" class="form-control form-inline">
       </div>`).insertBefore(target);
        ++opening_time_index
    }

    $(`select[name='${fieldPrefix}[room_ids][]'] option`).on('pointerdown', function(e) {
        e.preventDefault();
        $(this).prop('selected', !$(this).prop('selected'));
        $(this).parent().focus()
        return false;
    });

</script>

app/views/people/edit.html.erb
<div class="row pb-1">
  <div class="col-lg-6 col-md-6 mx-auto">
    <h2 class="fw-light"><%= t('model.edit', model: t('people.one')) %></h2>

    <%= render 'form', person: @person %>

    <%= link_to t("back"), people_path, class: "btn btn-secondary link-btn" %>
    <%= link_to t("show"), @person, class: "btn btn-secondary link-btn" %>
  </div>
</div>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="fw-light">People</h1>

<div class="table-responsive">
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= t('people.first_name') %></th>
      <th><%= t('people.last_name') %></th>
      <th><%= t('email') %></th>
      <th><%= t('people.phone_number') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.first_name %></td>
        <td><%= person.last_name %></td>
        <td><%= mail_to person.email %></td>
        <td><%= tel_to person.phone_number %></td>
        <td class="td-btn"><%= link_to t(:show), person, class: "btn btn-secondary link-btn"  %></td>
        <td class="td-btn"><% if can? :update, person %><%= link_to t(:edit), edit_person_path(person), class: "btn btn-secondary link-btn"  %><%end%></td>
        <td class="td-btn"><% if can? :destroy, person %><%= link_to t(:destroy), person, method: :delete, data: { confirm: t(:confirm) }, class: "btn btn-secondary link-btn" %><%end%></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

<% if can? :create, Person %>
  <%= link_to t('model.add_new', model: t('people.one')), new_person_path, class: "btn btn-primary link-btn"%>
<% end %>

app/views/people/new.html.erb
<h1><%= t('people.new') %></h1>

<%= render 'form', person: @person %>

<%= link_to t("home"), root_url, class: "btn btn-secondary link-btn" %>
<%= link_to t("cancel"), edit_user_registration_path, class: "btn btn-secondary link-btn" %>

app/views/people/show.html.erb
<% if current_user %>
<button id="person-favourite" class="favourite <% if @person.favourited_by.include?(current_user) %> selected <% end %>" title="<%= t('favourite') %>">
    <i class="far fa-heart"></i>
    <i class="fas fa-heart"></i>
</button>
<% end %>

<h2 class="mb-3 fw-light">
  <%= @person.first_name %>
  <%= @person.last_name %>
</h2>

<div class="mb-3 profile-picture show-profile-picture">
  <div class='profile-picture-wrapper'>
    <div class='profile-picture-container'>
      <% if @person.profile_picture.attached? %>
        <img src="<%=(url_for(@person.profile_picture))%>" alt="<%= @person.profile_picture.filename %>"/>
      <% else %>
        <%= image_tag "default-profile-picture.png", alt: "default-profile-picture"%>
      <% end %>
    </div>
  </div>
</div>

<p>
  <strong><%= "#{t(:email)}:" %></strong>
  <%= mail_to @person.email %>
</p>

<p>
  <strong><%= "#{t('people.phone_number')}:" %></strong>
  <%= tel_to @person.phone_number %>
</p>

<% person_loc = @person.corresponding_user&.last_known_location %>
<% if not person_loc.nil? %>
  <p>
    <strong><%= "#{t('people.last_known_location')}:" %></strong>
    <a href="/route?dest=<%= person_loc %>">
      <%= person_loc %>
    </a>
  </p>
<% end %>

<p>
  <strong><%= "#{t('rooms.other')}:" %></strong>
  <ul class="container">
      <% @person.rooms.each do | room | %>
        <li class="row">
          <span class="col">
            <%= link_to room.name, room_path(room) %>
          </span>
          <span class="col-auto ms-auto">
            <a class="btn btn-outline-primary btn-sm" href="/route?dest=<%= room.name %>">
              <i class="fas fa-route"></i> <%= t("buildings.directions") %>
            </a>
          </span>
        </li>
      <% end %>
  </ul>
</p>

<p>
  <strong><%= "#{t('people.office_hour.other')}:" %></strong>
  <ul>
    <% @person.openingtimes.each do | opening_time | %>
      <li>
        <%= opening_time.to_string %>
      </li>
    <% end %>
  </ul>
</p>

<script defer>
  $('#person-favourite').click(async function (e) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute("content") ?? "";
    let becomesFavourite = !e.currentTarget.classList.contains("selected");

    const body = JSON.stringify({
      favourite: becomesFavourite
    });
    const response = await fetch(
      `/people/<%= @person.id %>/favourite`,
      {
        method: "PUT",
        body: body,
        headers: {
          "X-CSRF-TOKEN": csrfToken,
          "Content-Type": "application/json",
        },
      }
    );
    console.assert(response.status === 204); // HTTP "No content"

    if(becomesFavourite) {
      e.currentTarget.classList.add("selected")
    } else {
      e.currentTarget.classList.remove("selected")
    }

  })
</script>