config/routes.rb
Rails.application.routes.draw do
  get 'error/show'
  resources :events do
    collection { post :import }
  end
  resources :people

  get '/favourites', to: 'favourites#list', as: 'get_favourites'
  put '/rooms/:id/favourite', to: 'favourites#set_favourite_room', as: 'put_favourite_rooms'
  put '/buildings/:id/favourite', to: 'favourites#set_favourite_building', as: 'put_favourite_buildings'
  put '/locations/:id/favourite', to: 'favourites#set_favourite_location', as: 'put_favourite_locations'
  put '/people/:id/favourite', to: 'favourites#set_favourite_person', as: 'put_favourite_people'
  resources :rooms do
    get 'calendar'
  end

  resources :openingtimes
  resources :buildings
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # '/users/...'
  # https://github.com/plataformatec/devise#configuring-routes
  devise_for :users, path: 'users',
    controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  # '/login'
  get '/login', to: 'welcome#login'

  # '/building/map'
  get '/building_map/route', to: 'building_map#route'
  get '/building_map/view', to: 'building_map#view'

  # '/search_results'
  get '/search_results', to: 'search_results#index'

  put '/users/geo_location', to: 'users/geo_locations#update'
  delete '/users/geo_location', to: 'users/geo_locations#delete'

  # '/calendar'
  get '/calendar', to: 'calendar#show'

  # '/'
  # Sets `root_url`, devise gem requires this to be set
  root to: "welcome#index"

  get '/map/*path' => "welcome#index", as: 'map'

  get 'users/roles'
  put '/users/:id/roles', to: 'users#update_roles'
end

app/models/event.rb
require 'icalendar'
require 'ice_cube'
require 'json'
require 'yaml'
require 'date'
require 'time'

# the model representing an event in the calendar
class Event < ApplicationRecord
  belongs_to :room, optional: true
  validates :name, :start_time, :end_time, presence: true

  def self.import(file)
    calendars = Icalendar::Calendar.parse(file.read.force_encoding("UTF-8"))
    calendars.each do |calendar|
      calendar.events.each do |parse_event|
        create_from_icalendar(parse_event)
      end
    end
  end

  def self.generate_calendar_events(events, start_date, end_date)
    events.flat_map { |event| event.calendar_events(start_date, end_date) }
  end

  def start_hour_minute
    start_time.strftime('%H:%M')
  end

  def end_hour_minute
    end_time.strftime('%H:%M')
  end

  def rule
    IceCube::Rule.from_yaml(recurring) if recurring.present?
  end

  def schedule
    schedule = IceCube::Schedule.new(start_time, end_time: end_time)
    schedule.add_recurrence_rule(rule)
    schedule
  end

  def search_description
    description
  end

  def calendar_events(start_date, end_date)
    if recurring.blank?
      [self] if (start_date..end_date).cover?(start_time) || (start_date..end_date).cover?(end_time)
    else
      schedule.occurrences_between(start_date, end_date).map do |occurrence|
        Event.new(id: id, name: name, description: description, start_time: occurrence.start_time,
                  end_time: occurrence.end_time, room: room)
      end
    end
  end

  def self.ical_rule_to_ice_cube_yaml(rrule)
    rrule_yaml = ""
    unless rrule.nil?
      rrule_ics = "FREQ=#{rrule.frequency}"
      rrule_ics << single_parameter_ics_values(rrule)
      rrule_ics << multi_parameter_ics_values(rrule)
      rrule_yaml = IceCube::Rule.from_ical(rrule_ics).to_yaml
    end
    rrule_yaml
  end

  def self.single_parameter_ics_values(rrule)
    values = rrule.to_h.fetch_values :interval, :count, :until, :week_start
    strings = %w[INTERVAL COUNT UNTIL WKST]

    rrule_ics = ""
    values.zip(strings).each do |value, string|
      rrule_ics << ";#{string}=#{value}" unless value.nil?
    end
    rrule_ics
  end

  def self.multi_parameter_ics_values(rrule)
    values = rrule.to_h.fetch_values :by_second, :by_minute, :by_hour, :by_day, :by_month_day, :by_month, :by_year_day
    strings = %w[BYSECOND BYMINUTE BYHOUR BYDAY BYMONTHDAY BYMONTH BYYEARDAY]

    rrule_ics = ""
    values.zip(strings).each do |value, string|
      rrule_ics << ";#{string}=#{value.join(',')}" unless value.nil?
    end
    rrule_ics
  end

  def self.create_from_icalendar(event)
    create(name: event.summary,
           start_time: event.dtstart,
           end_time: event.dtend,
           description: event.description.nil? ? "" : event.description,
           recurring: ical_rule_to_ice_cube_yaml(event.rrule.first),
           room: Room.find_by(name: event.location.to_s))
  end

  def queried_occurence
    schedule.next_occurrence || schedule.last
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: %i[show edit update destroy]
  before_action :add_event, only: %i[create]

  # GET /events or /events.json
  def index
    @events = Event.all
  end

  def import
    if params[:file].nil?
      redirect_to edit_user_registration_path, alert: t('events.alert.choose_file')
    else
      import_ics(params[:file].tempfile)
    end
  end

  # GET /events/1 or /events/1.json
  def show; end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit; end

  # POST /events or /events.json
  def create
    respond_to do |format|
      if @event.save
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.create', model: t('events.one'))
        end
        format.json { render :show, status: :created, location: @event }
      else
        render_errors format, :new
      end
    end
  end

  # PATCH/PUT /events/1 or /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.update', model: t('events.one'))
        end
        format.json { render :show, status: :ok, location: @event }
      else
        render_errors format, :edit
      end
    end
  end

  # DELETE /events/1 or /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html do
        redirect_to edit_user_registration_path, notice: t('model.success.destroy', model: t('events.one'))
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_event
    @event = Event.find(params[:id])
  end

  def add_event
    @event = Event.new(event_params)
  end

  def render_errors(format, route)
    format.html { render route, status: :unprocessable_entity }
    format.json { render json: @event.errors, status: :unprocessable_entity }
  end

  # Only allow a list of trusted parameters through.
  def event_params
    params.require(:event).permit(:name, :description, :start_time, :end_time, :recurring, :room_id)
  end

  def import_ics(file)
    if File.extname(file.path) == ".ics"
      Event.import(file)
      redirect_to edit_user_registration_path, notice: t('events.import_success')
    else
      redirect_to edit_user_registration_path, alert: t('events.alert.ics_only')
    end
    file.close!
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', count: @event.errors.count, model: t('events.one')) %></h2>

      <ul>
        <% event.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t(:name), class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label t(:description), class: "form-label" %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

    <div>
      <%= form.label t('rooms.one'), class: "form-label" %>
      <%= form.select 'room_id',
          options_from_collection_for_select(
            Room.all, :id, :name, event.room.nil? ? 1 : event.room.id) + options_for_select([["No Room", nil]]),
          {},
          multiple: false, class: "form-control" %>
    </div>

  <div class="field">
    <%= form.label t('events.start_date'), class: "form-label" %>
    <%= form.datetime_select :start_time, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label t('events.end_date'), class: "form-label" %>
    <%= form.datetime_select :end_time, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label t('events.recurrence_rule'), class: "form-label" %>
    <%= form.text_area :recurring, class: "form-control" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit t('model.create', model: t('events.one')), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<div class="row pb-1">
  <div class="col-lg-6 col-md-6 mx-auto">
    <h2 class="fw-light">Edit Event</h2>

    <%= render 'form', event: @event %>

    <%= link_to t("home"), root_url, class: "btn btn-secondary link-btn" %>
    <%= link_to t("cancel"), edit_user_registration_path, class: "btn btn-secondary link-btn" %>
  </div>
</div>

app/views/events/index.html.erb
<h1 class="fw-light"><%= t('events.other') %></h1>

<%= form_tag import_events_path, multipart: true, class: 'form-inline' do %>
  <div class="form-group mb-2">
    <%= file_field_tag :file, class: 'attachment' %>
  </div>

  <div class="col-sm-10">
    <%= submit_tag "Import ICS", class: 'btn btn-primary mb-2' %>
  </div>
<% end %>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t(:name)%></th>
        <th><%= t(:description)%></th>
        <th><%= t('rooms.one')%></th>
        <th><%= t('events.start_date')%></th>
        <th><%= t('events.end_date')%></th>
        <th><%= t('events.recurrence_rule')%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @events.each do |event| %>
        <tr>
          <td><%= event.name %></td>
          <td><%= event.description %></td>
          <% if event.room.nil? then %>
            <td><%= t('events.no_room') %></td>
          <% else %>
            <td><%= link_to event.room.name, room_path(event.room) %></td>
          <% end %>
          <td><%= event.start_time.to_s %></td>
          <td><%= event.end_time.to_s %></td>
          <td><%= event.rule %></td>
          <td><%= link_to t("show"), event %></td>
          <td><%= link_to t('edit'), edit_event_path(event) %></td>
          <td><%= link_to t('destroy'), event, method: :delete, data: { confirm: t(:confirm) } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<%= link_to t('model.add_new', model: t('events.one')), new_event_path %>

app/views/events/new.html.erb
<h1><%= t('events.new')%></h1>

<%= render 'form', event: @event %>

<%= link_to t("home"), root_url, class: "btn btn-secondary link-btn" %>
<%= link_to t("cancel"), edit_user_registration_path, class: "btn btn-secondary link-btn" %>

app/views/events/show.html.erb
<h2 class="mb-3 fw-light"><%= @event.name %></h2>

<div class="td-btn"><%= link_to t('calendar'), calendar_path(event_id: @event.id, start_date: @event.queried_occurence), class: "btn btn-secondary link-btn" %></div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t(:description)}:" %></strong>
  </label>
  <p class="form-control-static">
    <%= @event.description %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t('events.start_date')}:"%></strong>
  </label>
  <p class="form-control-static">
    <%= @event.start_time.to_s %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t('events.end_date')}:"%></strong>
  </label>
  <p class="form-control-static">
    <%= @event.end_time.to_s %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t('rooms.one')}:"%></strong>
  </label>
  <p class="form-control-static">
    <% if @event.room.nil? then %>
      <td><%= "No Room" %></td>
    <% else %>
      <td><%= link_to @event.room.name, room_path(@event.room) %></td>
    <% end %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t('events.start_date')}:"%></strong>
  </label>
  <p class="form-control-static">
    <%= @event.rule %>
  </p>
</div>

<% if @event.room %>
  <script id="_latlonginfo" type="application/json">
  [<%= @event.room.building.location_latitude %>,<%= @event.room.building.location_longitude %>]
  </script>
<% end %>