config/routes.rb
Rails.application.routes.draw do
  get 'error/show'
  resources :events do
    collection { post :import }
  end
  resources :people

  get '/favourites', to: 'favourites#list', as: 'get_favourites'
  put '/rooms/:id/favourite', to: 'favourites#set_favourite_room', as: 'put_favourite_rooms'
  put '/buildings/:id/favourite', to: 'favourites#set_favourite_building', as: 'put_favourite_buildings'
  put '/locations/:id/favourite', to: 'favourites#set_favourite_location', as: 'put_favourite_locations'
  put '/people/:id/favourite', to: 'favourites#set_favourite_person', as: 'put_favourite_people'
  resources :rooms do
    get 'calendar'
  end

  resources :openingtimes
  resources :buildings
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # '/users/...'
  # https://github.com/plataformatec/devise#configuring-routes
  devise_for :users, path: 'users',
    controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  # '/login'
  get '/login', to: 'welcome#login'

  # '/building/map'
  get '/building_map/route', to: 'building_map#route'
  get '/building_map/view', to: 'building_map#view'

  # '/search_results'
  get '/search_results', to: 'search_results#index'

  put '/users/geo_location', to: 'users/geo_locations#update'
  delete '/users/geo_location', to: 'users/geo_locations#delete'

  # '/calendar'
  get '/calendar', to: 'calendar#show'

  # '/'
  # Sets `root_url`, devise gem requires this to be set
  root to: "welcome#index"

  get '/map/*path' => "welcome#index", as: 'map'

  get 'users/roles'
  put '/users/:id/roles', to: 'users#update_roles'
end

app/models/building.rb
class Building < ApplicationRecord
  has_and_belongs_to_many :owners, class_name: 'User', join_table: 'building_owner'
  include Timeable
  include Locateable
  include Favourable
  validates :name, presence: true
end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  load_and_authorize_resource
  before_action :set_building, only: %i[show edit update destroy]
  before_action :add_building, only: %i[create]

  # GET /buildings or /buildings.json
  def index
    @buildings = Building.all
  end

  # GET /buildings/1 or /buildings/1.json
  def show; end

  # GET /buildings/new
  def new
    @building = Building.new
    @latitude = params[:lat]
    @longitude = params[:long]
  end

  # GET /buildings/1/edit
  def edit; end

  # POST /buildings or /buildings.json
  # rubocop:disable Metrics/MethodLength
  def create
    @building.owners = [current_user]
    respond_to do |format|
      if @building.save
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.create', model: t('buildings.one'))
        end
        format.json { render :edit, status: :created, location: @building }
      else
        render_errors format, :new
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /buildings/1 or /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.update', model: t('buildings.one'))
        end
        format.json { render :edit, status: :ok, location: @building }
      else
        render_errors format, :edit
      end
    end
  end

  # DELETE /buildings/1 or /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html do
        redirect_to edit_user_registration_path, notice: t('model.success.destroy', model: t('buildings.one'))
      end
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_building
    @building = Building.find(params[:id])
  end

  def add_building
    @building = Building.new(building_params)
  end

  def render_errors(format, route)
    format.html { render route, status: :unprocessable_entity }
    format.json { render json: @building.errors, status: :unprocessable_entity }
  end

  # Only allow a list of trusted parameters through.
  def building_params
    params.require(:building).permit(:name, :name_de, :location_latitude, :location_longitude)
  end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_with(model: building) do |form| %>
  <% if building.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', count: @building.errors.count, model: t('buildings.one')) %></h2>

      <ul>
        <% building.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label :name_de, class: "form-label" %>
    <%= form.text_field :name_de, class: "form-control"%>
  </div>

  <div class="field">
    <%= form.label t("buildings.latitude"), class: "form-label" %>
    <%= form.text_field :location_latitude, class: "form-control", value: latitude %>
  </div>

  <div class="field">
    <%= form.label t("buildings.longitude"), class: "form-label" %>
    <%= form.text_field :location_longitude, class: "form-control", value: longitude %>
  </div>

  <div class="actions mt-3">
    <%= form.submit t('model.create', model: t('buildings.one')), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<div class="row pb-1">
  <div class="col-lg-6 col-md-6 mx-auto">
  
    <h2 class="fw-light"> <%= t("edit_building")%> </h2>
    <h2 class="fw-light"><%= t('model.edit', model: t('buildings.one')) %></h2>

    <%= render 'form', building: @building, latitude: @building.location_latitude, longitude: @building.location_longitude%>

    <%= link_to t("back"), buildings_path, class: "btn btn-secondary link-btn" %>
    <%= link_to t("show"), @building, class: "btn btn-secondary link-btn" %>
  </div>
</div>

app/views/buildings/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="fw-light"><%= t("buildings.other")%></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t('locations.latitude')%></th>
        <th><%= t('locations.longitude')%></th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @buildings.each do |building| %>
        <tr>
          <td><%= building.name %></td>
          <td><%= building.location_latitude %></td>
          <td><%= building.location_longitude %></td>
          <td class="td-btn"><%= link_to t("show"), building, class: "btn btn-secondary link-btn" %></td>
          <td class="td-btn"><% if can? :update, building %><%= link_to 'Edit', edit_building_path(building), class: "btn btn-secondary link-btn" %><%end%></td>
          <td class="td-btn"><% if can? :destroy, building %><%= link_to 'Destroy', building, method: :delete, data: { confirm: t(:confirm) }, class: "btn btn-secondary link-btn" %><%end%></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br>

<% if can? :create, Building%>
  <%= link_to t('add_new.new'), new_building_path, class: "btn btn-primary link-btn" %>
<% end %>

app/views/buildings/new.html.erb
<h1><%= t('buildings.new') %></h1>

<%= render 'form', building: @building, longitude: @longitude, latitude: @latitude%>

<%= link_to t("home"), root_url, class: "btn btn-secondary link-btn" %>
<%= link_to t("cancel"), edit_user_registration_path, class: "btn btn-secondary link-btn" %>

app/views/buildings/show.html.erb
<h2 class="mb-3 fw-light">
  <%= if I18n.locale == :de
        @building.name_de.nil? || @building.name_de.empty? ? @building.name : @building.name_de
      elsif I18n.locale == :en
        @building.name
      end%>
</h2>
<% if current_user %>
<button id="building-favourite" class="favourite <% if @building.favourited_by.include?(current_user) %> selected <% end %>" title="<%= t('favourite') %>">
    <i class="far fa-heart"></i>
    <i class="fas fa-heart"></i>
</button>
<% end %>


<div class="field mb-3">
  <label class="form-label">
    <strong>
      <%=t("name")%>:
    </strong>
  </label>
  <p class="form-control-static">
  <%= if I18n.locale == :de
        @building.name_de.nil? || @building.name_de.empty? ? @building.name : @building.name_de
      elsif I18n.locale == :en
        @building.name
      end%>
  </p>
</div>

<a class='btn btn-primary' href='/route?dest=<%= @building.name %>'>
  <i class='fas fa-route'></i> <%= t("buildings.directions") %>
</a>

<script id="_latlonginfo" type="application/json">
[<%= @building.location_latitude %>,<%= @building.location_longitude %>]
</script>

<script defer>
  $('#building-favourite').click(async function (e) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute("content") ?? "";
    let becomesFavourite = !e.currentTarget.classList.contains("selected");

    const body = JSON.stringify({
      favourite: becomesFavourite
    });
    const response = await fetch(
      `/buildings/<%= @building.id %>/favourite`,
      {
        method: "PUT",
        body: body,
        headers: {
          "X-CSRF-TOKEN": csrfToken,
          "Content-Type": "application/json",
        },
      }
    );
    console.assert(response.status === 204); // HTTP "No content"

    if(becomesFavourite) {
      e.currentTarget.classList.add("selected")
    } else {
      e.currentTarget.classList.remove("selected")
    }

  })
</script>