config/routes.rb
Rails.application.routes.draw do
  get 'error/show'
  resources :events do
    collection { post :import }
  end
  resources :people

  get '/favourites', to: 'favourites#list', as: 'get_favourites'
  put '/rooms/:id/favourite', to: 'favourites#set_favourite_room', as: 'put_favourite_rooms'
  put '/buildings/:id/favourite', to: 'favourites#set_favourite_building', as: 'put_favourite_buildings'
  put '/locations/:id/favourite', to: 'favourites#set_favourite_location', as: 'put_favourite_locations'
  put '/people/:id/favourite', to: 'favourites#set_favourite_person', as: 'put_favourite_people'
  resources :rooms do
    get 'calendar'
  end

  resources :openingtimes
  resources :buildings
  resources :locations
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  # '/users/...'
  # https://github.com/plataformatec/devise#configuring-routes
  devise_for :users, path: 'users',
    controllers: {
      registrations: 'users/registrations',
      omniauth_callbacks: 'users/omniauth_callbacks'
    }

  # '/login'
  get '/login', to: 'welcome#login'

  # '/building/map'
  get '/building_map/route', to: 'building_map#route'
  get '/building_map/view', to: 'building_map#view'

  # '/search_results'
  get '/search_results', to: 'search_results#index'

  put '/users/geo_location', to: 'users/geo_locations#update'
  delete '/users/geo_location', to: 'users/geo_locations#delete'

  # '/calendar'
  get '/calendar', to: 'calendar#show'

  # '/'
  # Sets `root_url`, devise gem requires this to be set
  root to: "welcome#index"

  get '/map/*path' => "welcome#index", as: 'map'

  get 'users/roles'
  put '/users/:id/roles', to: 'users#update_roles'
end

app/models/room.rb
# the model representing a room
class Room < ApplicationRecord
  has_and_belongs_to_many :owners, class_name: 'User', join_table: 'room_owner'
  belongs_to :building
  has_many :events, dependent: nil
  has_and_belongs_to_many :people

  include Favourable
  include Locateable

  validates :name, presence: true
  validates :floor, presence: true, numericality: { only_integer: true }

  def free?
    room_events = Event.where room: self
    room_events.each do |event|
      return false if event.schedule.occurring_at?(Time.zone.now)
    end
    true
  end

  def self.room_type_to_internal_mapping
    {
      'Lecture hall' => 'lecture-hall',
      'Pool room' => 'pool-room',
      'Seminar room' => 'seminar-room',
      'Conference room' => 'conference-room'
    }
  end

  def self.room_type_to_external_mapping
    {
      'lecture-hall' => 'Lecture hall',
      'pool-room' => 'Pool room',
      'seminar-room' => 'Seminar room',
      'conference-room' => 'Conference room'
    }
  end

  def search_description
    I18n.t('rooms.search_description', type: room_type, floor: floor, building: building.name)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  load_and_authorize_resource
  before_action :set_room, only: %i[show edit update destroy]
  before_action :add_room, only: %i[create]

  # GET /rooms or /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1 or /rooms/1.json
  def show; end

  # GET /rooms/new
  def new
    @room = Room.new
    @latitude = params[:lat]
    @longitude = params[:long]
  end

  # GET /rooms/1/edit
  def edit; end

  # GET /rooms/1/calendar
  def calendar
    @room = Room.find(params[:room_id])
    start_date = params[:start_date].to_date
    @month = start_date.month
    @year = start_date.year
    @events = Event.generate_calendar_events(@room.events,
                                             start_date.beginning_of_month.beginning_of_week,
                                             start_date.end_of_month.end_of_week).compact
  end

  # POST /rooms or /rooms.json
  # rubocop:disable Metrics/MethodLength
  def create
    @room.owners = [current_user]
    respond_to do |format|
      if @room.save
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.create', model: t('rooms.one'))
        end
        format.json { render :edit, status: :created, location: @room }
      else
        render_errors format, :new
      end
    end
  end
  # rubocop:enable Metrics/MethodLength

  # PATCH/PUT /rooms/1 or /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html do
          redirect_to edit_user_registration_path, notice: t('model.success.update', model: t('rooms.one'))
        end
        format.json { render :edit, status: :ok, location: @room }
      else
        render_errors format, :edit
      end
    end
  end

  # DELETE /rooms/1 or /rooms/1.json
  def destroy
    @room.destroy
    respond_to do |format|
      format.html { redirect_to edit_user_registration_path, notice: t('model.success.destroy', model: t('rooms.one')) }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_room
    @room = Room.find(params[:id])
  end

  def add_room
    @room = Room.new(room_params)
  end

  def render_errors(format, route)
    format.html { render route, status: :unprocessable_entity }
    format.json { render json: @room.errors, status: :unprocessable_entity }
  end

  # Only allow a list of trusted parameters through.
  def room_params
    params.require(:room).permit(:name, :name_de, :floor, :room_type, :building_id,
                                 :location_latitude, :location_longitude, person_ids: [])
  end
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<%= form_with(model: room) do |form| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= t('errors.template.header', count: @room.errors.count, model: t('rooms.one')) %></h2>

      <ul>
        <% room.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, class: "form-label" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :name_de, class: "form-label" %>
    <%= form.text_field :name_de, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label t("buildings.latitude"), class: "form-label" %>
    <%= form.number_field :location_latitude, step: :any, class: "form-control", value: latitude %>
  </div>

  <div class="field">
    <%= form.label t("buildings.longitude"), class: "form-label" %>
    <%= form.number_field :location_longitude, step: :any, class: "form-control", value: longitude %>
  </div>

  <div class="field">
    <%= form.label t("rooms.floor"), class: "form-label" %>
    <%= form.text_field :floor, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label t("rooms.type"), class: "form-label" %>
    <!--<%= form.text_field :room_type, class: "form-control" %>-->
    <%= form.select 'room_type',
      options_for_select(Room.room_type_to_internal_mapping, room.room_type),
      {},
      multiple: false, class: "form-control form-inline" %>
  </div>

  <div>
    <%= form.label :building_id, class: "form-label" %>
      <%= form.select 'building_id',
          options_from_collection_for_select(Building.all, :id, :name),
          {},
          multiple: false, class: "form-control" %>
  </div>

  <div>
    <%= form.label t('people.other'), class: "form-label" %>
      <%= form.select 'person_ids',
          options_from_collection_for_select(Person.all, :id, :name, room.person_ids),
          {},
          multiple: true, class: "form-control" %>
  </div>

  <div class="actions mt-3">
    <%= form.submit t('model.create', model: t('rooms.one')), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/rooms/calendar.html.erb
<h1><%= @room.name %></h1>
<% @params[:room_id] = @room.id if !@params.nil? %>

<h2><%= t('date.month_names')[@month] %> <%= @year %></h2>
<%= week_calendar(number_of_weeks: 1, events: @events) do |date, events| %>
  <%= date.day %>
  <% events.each do |event| %>
          <div class="content" >
            <%=  event.start_hour_minute %>
            <%=  event.name %>
          </div>
    </div>
  <% end %> 
<% end %>

app/views/rooms/edit.html.erb
<div class="row pb-1">
  <div class="col-lg-6 col-md-6 mx-auto">
    <h2 class="fw-light"><%= t('model.edit', model: t('rooms.one')) %></h2>

    <%= render 'form', room: @room, latitude: @room.location_latitude, longitude: @room.location_longitude %>

    <%= link_to t("back"), rooms_path, class: "btn btn-secondary link-btn" %>
    <%= link_to t("show"), @room, class: "btn btn-secondary link-btn" %>
  </div>
</div>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="fw-light"><%= t("rooms.other")%></h1>

<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th><%= t(:name) %></th>
        <th><%= t("rooms.floor") %></th>
        <th><%= t("rooms.occupancy")%></th>
        <th colspan="4"></th>
      </tr>
    </thead>

    <tbody>
      <% Room.room_type_to_external_mapping.each do |internal,external| %>
      <tr>
        <th colspan="7"><b><%= external.pluralize() %>:</b></th>
      </tr>
      <% @rooms.each do |room| %>
        <% if room.room_type == internal %>
          <tr>
            <td><%= room.name %></td>
            <td><%= room.floor %></td>
            <td>
              <% if room.free? %>
                <p class="occupancy free"><%= t("rooms.free")%></p>
              <% else %>
                <p class="occupancy occupied"><%= t("rooms.occupied")%></p>
              <% end %>
            </td>
            <td class="td-btn"><%= link_to 'Calendar', room_calendar_path(room, start_date: Time.zone.today.beginning_of_week.to_s), class: "btn btn-secondary link-btn" %></td>
            <td class="td-btn"><%= link_to t("show"), room, class: "btn btn-secondary link-btn" %></td>
            <td class="td-btn"><% if can? :update, room %><%= link_to 'Edit', edit_room_path(room), class: "btn btn-secondary link-btn"  %><%end%></td>
            <td class="td-btn"><% if can? :destroy, room %><%= link_to 'Destroy', room, method: :delete, data: { confirm: t(:confirm) }, class: "btn btn-secondary link-btn" %><%end%></td>
          </tr>
        <% end %>
      <% end %>
    <% end %>
    </tbody>
  </table>
</div>


<% if can? :create, Room %>
  <%= link_to 'New Room', new_room_path, class: "btn btn-primary link-btn" %>
<% end %>

app/views/rooms/new.html.erb
<h1><%= t('rooms.new') %></h1>

<%= render 'form', room: @room, longitude: @longitude, latitude: @latitude %>

<%= link_to t("home"), root_url, class: "btn btn-secondary link-btn" %>
<%= link_to t("cancel"), edit_user_registration_path, class: "btn btn-secondary link-btn" %>

app/views/rooms/show.html.erb
<% if current_user %>
<button id="room-favourite" class="favourite <% if @room.favourited_by.include?(current_user) %> selected <% end %>" title="<%= t('favourite') %>">
    <i class="far fa-heart"></i>
    <i class="fas fa-heart"></i>
</button>
<% end %>

<div class="row">
    <div class="col-md-4">
        <h2 class="mb-3 fw-light"> 
        <%= if I18n.locale == :de
              @room.name_de
            elsif I18n.locale == :en
              @room.name
            end%></h2>
    </div>
    <div class="col-md-8 align-self-center">
        <% if @room.free? %>
          <p class="occupancy free"><%= t("rooms.free") %></p>
        <% else %>
          <p class="occupancy occupied"><%= t("rooms.occupied") %></p>
        <% end %>
    </div>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= "#{t(:name)}:" %></strong>
  </label>
  <p class="form-control-static">
    <%= @room.name %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= t("rooms.floor")%>:</strong>
  </label>
  <p class="form-control-static">
    <%= @room.floor %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= t("buildings.longitude")%>:</strong>
  </label>
  <p class="form-control-static">
    <%= @room.location_longitude %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= t("buildings.latitude")%>:</strong>
  </label>
  <p class="form-control-static">
    <%= @room.location_latitude %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    <strong><%= t("rooms.type")%>:</strong>
  </label>
  <p class="form-control-static">
    <%= Room.room_type_to_external_mapping[@room.room_type] %>
  </p>
</div>

<div class="field mb-3">
  <label class="form-label">
    </label><strong><%= t('people.other') %>:</strong>
  </label>
  <ul>
    <p class="form-control-static">
      <% @room.people.each do | person | %>
        <li>
          <%= link_to person.name, person_path(person) %>
        </li>
      <% end %>
    </p>
  </ul>
</div>

<div class="td-btn"><%= link_to t('calendar'), room_calendar_path(@room, start_date: Time.zone.today.beginning_of_week.to_s), class: "btn btn-secondary link-btn" %></div>

<a class="btn btn-primary" href="/route?dest=<%= @room.name %>">
  <i class="fas fa-route"></i> <%= t("buildings.directions") %>
</a>

<script id="_latlonginfo" type="application/json">
[<%= @room.location_latitude %>,<%= @room.location_longitude %>]
</script>

<script id="_floorinfo" type="application/json">
<%= @room.floor %>
</script>

<script defer>
  $('#room-favourite').click(async function (e) {
    const csrfToken = document.querySelector('meta[name="csrf-token"]')?.getAttribute("content") ?? "";
    let becomesFavourite = !e.currentTarget.classList.contains("selected");

    const body = JSON.stringify({
      favourite: becomesFavourite
    });
    const response = await fetch(
      `/rooms/<%= @room.id %>/favourite`,
      {
        method: "PUT",
        body: body,
        headers: {
          "X-CSRF-TOKEN": csrfToken,
          "Content-Type": "application/json",
        },
      }
    );
    console.assert(response.status === 204); // HTTP "No content"

    if(becomesFavourite) {
      e.currentTarget.classList.add("selected")
    } else {
      e.currentTarget.classList.remove("selected")
    }

  })
</script>